### ISSUE TITLE
Invalid option "framework" for all commands

### ISSUE THREAD

**Issue by trzcina** [flotiq/flotiq-cli#60]
### To Reproduce

1. Type `node bin/flotiq start --help`
2. The response contains '--framework' option, this is ok
3. Type `node bin/flotiq import --help`
4. The response contains '--framework' option, which is not part of this command

![Desktop-screenshot (73)](https://user-images.githubusercontent.com/645716/198266895-99eead09-2f7c-4899-8c73-64d378b38e9d.png)

**Comment by KarolNet** [comment]
Resolved
